version: '3.7'

services:
  uvicorn:
    build: .
    container_name: endpoint-example
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - ./environments/dev.env
    networks:
      - endpoint
  nginx:
    image: nginx:alpine
    container_name: endpoint-nginx
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
      - ./environments/nginx/conf.d/:/etc/nginx/conf.d/
      - ./environments/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - endpoint
    depends_on:
      - uvicorn

networks:
  endpoint:
    driver: bridge